export const jsReserved = [
    "abstract",
    "arguments",
    "await",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "double",
    "else",
    "enum",
    "eval",
    "export",
    "extends",
    "false",
    "final",
    "finally",
    "float",
    "for",
    "function",
    "goto",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "int",
    "interface",
    "let",
    "long",
    "native",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "volatile",
    "while",
    "with",
    "yield",
];

export const jsObjPropMeth = [
    "Array",
    "Date",
    "eval",
    "function",
    "hasOwnProperty",
    "Infinity",
    "isFinite",
    "isNaN",
    "isPrototypeOf",
    "length",
    "Math",
    "NaN",
    "name",
    "Number",
    "Object",
    "prototype",
    "String",
    "toString",
    "undefined",
    "valueOf",
];

export const common200 = [
    "over",
    "new",
    "sound",
    "take",
    "only",
    "little",
    "work",
    "know",
    "place",
    "year",
    "live",
    "me",
    "back",
    "give",
    "most",
    "very",
    "after",
    "thing",
    "our",
    "just",
    "name",
    "good",
    "sentence",
    "man",
    "think",
    "say",
    "great",
    "where",
    "help",
    "through",
    "much",
    "before",
    "line",
    "right",
    "too",
    "mean",
    "old",
    "any",
    "same",
    "tell",
    "boy",
    "follow",
    "came",
    "want",
    "show",
    "also",
    "around",
    "form",
    "three",
    "small",
    "set",
    "put",
    "end",
    "does",
    "another",
    "well",
    "large",
    "must",
    "big",
    "even",
    "such",
    "because",
    "turn",
    "here",
    "why",
    "ask",
    "went",
    "men",
    "read",
    "need",
    "land",
    "different",
    "home",
    "us",
    "move",
    "try",
    "kind",
    "hand",
    "picture",
    "again",
    "change",
    "off",
    "play",
    "spell",
    "air",
    "away",
    "animal",
    "house",
    "point",
    "page",
    "letter",
    "mother",
    "answer",
    "found",
    "study",
    "still",
    "learn",
    "should",
    "America",
    "world",
];

export const common100 = [
    "the",
    "of",
    "and",
    "a",
    "to",
    "in",
    "is",
    "you",
    "that",
    "it",
    "he",
    "was",
    "for",
    "on",
    "are",
    "as",
    "with",
    "his",
    "they",
    "I",
    "at",
    "be",
    "this",
    "have",
    "from",
    "or",
    "one",
    "had",
    "by",
    "word",
    "but",
    "not",
    "what",
    "all",
    "were",
    "we",
    "when",
    "your",
    "can",
    "said",
    "there",
    "use",
    "an",
    "each",
    "which",
    "she",
    "do",
    "how",
    "their",
    "if",
    "will",
    "up",
    "other",
    "about",
    "out",
    "many",
    "then",
    "them",
    "these",
    "so",
    "some",
    "her",
    "would",
    "make",
    "like",
    "him",
    "into",
    "time",
    "has",
    "look",
    "two",
    "more",
    "write",
    "go",
    "see",
    "number",
    "no",
    "way",
    "could",
    "people",
    "my",
    "than",
    "first",
    "water",
    "been",
    "call",
    "who",
    "oil",
    "its",
    "now",
    "find",
    "long",
    "down",
    "day",
    "did",
    "get",
    "come",
    "made",
    "may",
    "part",
];

// SOURCE: https://www3.nd.edu/~busiforc/handouts/cryptography/Letter%20Frequencies.html
export const bigrams = [
    "th",
    "he",
    "in",
    "en",
    "nt",
    "re",
    "er",
    "an",
    "ti",
    "es",
    "on",
    "at",
    "se",
    "nd",
    "or",
    "ar",
    "al",
    "te",
    "co",
    "de",
    "to",
    "ra",
    "et",
    "ed",
    "it",
    "sa",
    "em",
    "ro",
];

export const trigrams = [
    "the",
    "and",
    "tha",
    "ent",
    "ing",
    "ion",
    "tio",
    "for",
    "nde",
    "has",
    "nce",
    "edt",
    "tis",
    "oft",
    "sth",
    "men",
];

export const quadrigrams = [
    "that",
    "ther",
    "with",
    "tion",
    "here",
    "ould",
    "ight",
    "have",
    "hich",
    "whic",
    "this",
    "thin",
    "they",
    "atio",
    "ever",
    "from",
    "ough",
    "were",
    "hing",
    "ment",
];

export const topRow = [
    "Piroque", "Poutier", "Wipeout", "Equipt", "Equity", "Piquet",
    "Poetry", "Pouter", "Purity", "Pyrite", "Quoter", "Qwerty",
    "Roquet", "Torque", "Towery", "Troupe", "Typier", "Uptore",
    "Equip", "Erupt", "Outer", "Outre", "Pewit", "Piety",
    "Pique", "Pouty", "Power", "Purty", "Query", "Quiet",
    "Quire", "Quirt", "Quite", "Quoit", "Quote", "Repot",
    "Ropey", "Roque", "Route", "Tepoy", "Toper", "Toque",
    "Tower", "Towie", "Tripe", "Trope", "Twerp", "Twirp",
    "Twyer", "Uteri", "Wiper", "Write", "Wrote", "Etui",
    "Euro", "Peri", "Pert", "Pier", "Pity", "Poet",
    "Pore", "Port", "Pour", "Pout", "Prey", "Prow",
    "Pure", "Puri", "Pyre", "Pyro", "Quip", "Quit",
    "Repo", "Riot", "Ripe", "Rite", "Rope", "Ropy",
    "Rote", "Roti", "Roup", "Rout", "Ryot", "Tier",
    "Tire", "Tiro", "Tope", "Tore", "Tori", "Tory",
    "Tour", "Towy", "Trey", "Trio", "Trip", "Trop",
    "Trow", "Troy", "True", "Type", "Typo", "Tyre",
    "Tyro", "Weir", "Wept", "Wert", "Wipe", "Wire",
    "Wiry", "Wore", "Wort", "Writ", "Yeti", "Yore",
    "Your", "Yurt", "Ire", "Opt", "Ore", "Ort",
    "Our", "Out", "Owe", "Per", "Pet", "Pew",
    "Pie", "Pit", "Poi", "Pot", "Pow", "Pro",
    "Pry", "Pur", "Put", "Rep", "Ret", "Rip",
    "Roe", "Rot", "Row", "Rue", "Rut", "Rye",
    "Tie", "Tip", "Toe", "Top", "Tor", "Tow",
    "Toy", "Try", "Two", "Ute", "Wet", "Wit",
    "Woe", "Wot", "Wry", "Wye", "Yep", "Yet",
    "Yew", "Yip", "You", "Yow", "Yup"
]
export const homeRow = [
    "ashfalls", "hallahs", "ashfall", "daggas"
    // skalds	hallah	salads	flasks
    // flash	skald	kakas	slags
    // jaggs	galas	hadal	slash
    // shahs	gaffs	algal	dagga
    // flask	dahls	daffs	lakhs
    // shags	halls	glass	sagas
    // kasha	salad	galls	shall
    // dadas	falls	salsa	shads
    // flags	alfas	saga	half
    // sags	fads	dhal	glad
    // lash	kaka	lads	fall
    // hall	gads	alfa	adds
    // gags	gaga	hash	dahl
    // agha	hajj	lass	gaff
    // alga	dahs	asks	gals
    // lags	jagg	alas	jags
    // flak	daff	lakh	dash
    // gala	 	 	
]
export const bottomRow = [
    // "bcnxv", "zxcm", "mbcnz", "bnvcnm", "zxcv", "vbnm", "mnxz", "nxv", "zmnx", "vbcn", "mvz", "vzxcmvx", "mnbxcvz"
    "zero", "zebra", "zigzag", "zipper", "zoo", "xenops", "xerox", "xiphias", "crony", "coal", "code", "cola",
    "vacuum", "vest", "violin", "volcano", "vote", "vowel", "balloon", "bee", "bird", "broom", "butterfly",
    "navigation", "net", "nine", "number", "mitten", "moon", "mouse"
]

export const punctMarks = [",", ".", "!", "?", ":", ";", "-", "'"];

// export default common100;

// BEGINNER KEY LEVELS
export const keysLevel_1 = ["j", "f"];
export const keysLevel_2 = ["u", "r", "k"];
export const keysLevel_3 = ["d", "e", "i"];
export const keysLevel_4 = ["c", "g", "n"];
export const keysLevel_5 = ["t", "s", "l"];
export const keysLevel_6 = ["o", "b", "a"];
export const keysLevel_7 = ["v", "h", "m"];
export const keysLevel_8 = ["w", "x", "q"];
export const keysLevel_9 = ["y", "p", "z"];

export const keyLevelsArray = [
    keysLevel_1,
    keysLevel_2,
    keysLevel_3,
    keysLevel_4,
    keysLevel_5,
    keysLevel_6,
    keysLevel_7,
    keysLevel_8,
    keysLevel_9,
];
