export const jsReserved = [
    "abstract",
    "arguments",
    "await",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "double",
    "else",
    "enum",
    "eval",
    "export",
    "extends",
    "false",
    "final",
    "finally",
    "float",
    "for",
    "function",
    "goto",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "int",
    "interface",
    "let",
    "long",
    "native",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "volatile",
    "while",
    "with",
    "yield",
];

export const jsObjPropMeth = [
    "Array",
    "Date",
    "eval",
    "function",
    "hasOwnProperty",
    "Infinity",
    "isFinite",
    "isNaN",
    "isPrototypeOf",
    "length",
    "Math",
    "NaN",
    "name",
    "Number",
    "Object",
    "prototype",
    "String",
    "toString",
    "undefined",
    "valueOf",
];

export const common200 = [
    "over",
    "new",
    "sound",
    "take",
    "only",
    "little",
    "work",
    "know",
    "place",
    "year",
    "live",
    "me",
    "back",
    "give",
    "most",
    "very",
    "after",
    "thing",
    "our",
    "just",
    "name",
    "good",
    "sentence",
    "man",
    "think",
    "say",
    "great",
    "where",
    "help",
    "through",
    "much",
    "before",
    "line",
    "right",
    "too",
    "mean",
    "old",
    "any",
    "same",
    "tell",
    "boy",
    "follow",
    "came",
    "want",
    "show",
    "also",
    "around",
    "form",
    "three",
    "small",
    "set",
    "put",
    "end",
    "does",
    "another",
    "well",
    "large",
    "must",
    "big",
    "even",
    "such",
    "because",
    "turn",
    "here",
    "why",
    "ask",
    "went",
    "men",
    "read",
    "need",
    "land",
    "different",
    "home",
    "us",
    "move",
    "try",
    "kind",
    "hand",
    "picture",
    "again",
    "change",
    "off",
    "play",
    "spell",
    "air",
    "away",
    "animal",
    "house",
    "point",
    "page",
    "letter",
    "mother",
    "answer",
    "found",
    "study",
    "still",
    "learn",
    "should",
    "America",
    "world",
];

export const numbers = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",

    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014",
    "2013",
    "2012",
    "2011",
    "2010",
    "2009",
    "2008",
    "2007",
    "2006",
    "2005",
    "2004",
    "2003",
    "2002",
    "2001",
    "2000",
    "1999",
    "1998",
    "1997",
    "1996",
    "1995",
    "1994",
    "1993",
    "1992",
    "1991",
    "1990",
    "1989",
    "1988",
    "1987",
    "1986",
    "1985",
    "1984",
    "1983",
];

export const common100 = [
    "the",
    "of",
    "and",
    "a",
    "to",
    "in",
    "is",
    "you",
    "that",
    "it",
    "he",
    "was",
    "for",
    "on",
    "are",
    "as",
    "with",
    "his",
    "they",
    "I",
    "at",
    "be",
    "this",
    "have",
    "from",
    "or",
    "one",
    "had",
    "by",
    "word",
    "but",
    "not",
    "what",
    "all",
    "were",
    "we",
    "when",
    "your",
    "can",
    "said",
    "there",
    "use",
    "an",
    "each",
    "which",
    "she",
    "do",
    "how",
    "their",
    "if",
    "will",
    "up",
    "other",
    "about",
    "out",
    "many",
    "then",
    "them",
    "these",
    "so",
    "some",
    "her",
    "would",
    "make",
    "like",
    "him",
    "into",
    "time",
    "has",
    "look",
    "two",
    "more",
    "write",
    "go",
    "see",
    "number",
    "no",
    "way",
    "could",
    "people",
    "my",
    "than",
    "first",
    "water",
    "been",
    "call",
    "who",
    "oil",
    "its",
    "now",
    "find",
    "long",
    "down",
    "day",
    "did",
    "get",
    "come",
    "made",
    "may",
    "part",
];

// SOURCE: https://www3.nd.edu/~busiforc/handouts/cryptography/Letter%20Frequencies.html
export const bigrams = [
    "th",
    "he",
    "in",
    "en",
    "nt",
    "re",
    "er",
    "an",
    "ti",
    "es",
    "on",
    "at",
    "se",
    "nd",
    "or",
    "ar",
    "al",
    "te",
    "co",
    "de",
    "to",
    "ra",
    "et",
    "ed",
    "it",
    "sa",
    "em",
    "ro",
];

export const trigrams = [
    "the",
    "and",
    "tha",
    "ent",
    "ing",
    "ion",
    "tio",
    "for",
    "nde",
    "has",
    "nce",
    "edt",
    "tis",
    "oft",
    "sth",
    "men",
];

export const quadrigrams = [
    "that",
    "ther",
    "with",
    "tion",
    "here",
    "ould",
    "ight",
    "have",
    "hich",
    "whic",
    "this",
    "thin",
    "they",
    "atio",
    "ever",
    "from",
    "ough",
    "were",
    "hing",
    "ment",
];

export const topRow = [
    "Piroque",
    "Poutier",
    "Wipeout",
    "Equipt",
    "Equity",
    "Piquet",
    "Poetry",
    "Pouter",
    "Purity",
    "Pyrite",
    "Quoter",
    "Qwerty",
    "Roquet",
    "Torque",
    "Towery",
    "Troupe",
    "Typier",
    "Uptore",
    "Equip",
    "Erupt",
    "Outer",
    "Outre",
    "Pewit",
    "Piety",
    "Pique",
    "Pouty",
    "Power",
    "Purty",
    "Query",
    "Quiet",
    "Quire",
    "Quirt",
    "Quite",
    "Quoit",
    "Quote",
    "Repot",
    "Ropey",
    "Roque",
    "Route",
    "Tepoy",
    "Toper",
    "Toque",
    "Tower",
    "Towie",
    "Tripe",
    "Trope",
    "Twerp",
    "Twirp",
    "Twyer",
    "Uteri",
    "Wiper",
    "Write",
    "Wrote",
    "Etui",
    "Euro",
    "Peri",
    "Pert",
    "Pier",
    "Pity",
    "Poet",
    "Pore",
    "Port",
    "Pour",
    "Pout",
    "Prey",
    "Prow",
    "Pure",
    "Puri",
    "Pyre",
    "Pyro",
    "Quip",
    "Quit",
    "Repo",
    "Riot",
    "Ripe",
    "Rite",
    "Rope",
    "Ropy",
    "Rote",
    "Roti",
    "Roup",
    "Rout",
    "Ryot",
    "Tier",
    "Tire",
    "Tiro",
    "Tope",
    "Tore",
    "Tori",
    "Tory",
    "Tour",
    "Towy",
    "Trey",
    "Trio",
    "Trip",
    "Trop",
    "Trow",
    "Troy",
    "True",
    "Type",
    "Typo",
    "Tyre",
    "Tyro",
    "Weir",
    "Wept",
    "Wert",
    "Wipe",
    "Wire",
    "Wiry",
    "Wore",
    "Wort",
    "Writ",
    "Yeti",
    "Yore",
    "Your",
    "Yurt",
    "Ire",
    "Opt",
    "Ore",
    "Ort",
    "Our",
    "Out",
    "Owe",
    "Per",
    "Pet",
    "Pew",
    "Pie",
    "Pit",
    "Poi",
    "Pot",
    "Pow",
    "Pro",
    "Pry",
    "Pur",
    "Put",
    "Rep",
    "Ret",
    "Rip",
    "Roe",
    "Rot",
    "Row",
    "Rue",
    "Rut",
    "Rye",
    "Tie",
    "Tip",
    "Toe",
    "Top",
    "Tor",
    "Tow",
    "Toy",
    "Try",
    "Two",
    "Ute",
    "Wet",
    "Wit",
    "Woe",
    "Wot",
    "Wry",
    "Wye",
    "Yep",
    "Yet",
    "Yew",
    "Yip",
    "You",
    "Yow",
    "Yup",
];
export const homeRow = [
    "ashfalls",
    "hallahs",
    "ashfall",
    "daggas",
    // skalds	hallah	salads	flasks
    // flash	skald	kakas	slags
    // jaggs	galas	hadal	slash
    // shahs	gaffs	algal	dagga
    // flask	dahls	daffs	lakhs
    // shags	halls	glass	sagas
    // kasha	salad	galls	shall
    // dadas	falls	salsa	shads
    // flags	alfas	saga	half
    // sags	fads	dhal	glad
    // lash	kaka	lads	fall
    // hall	gads	alfa	adds
    // gags	gaga	hash	dahl
    // agha	hajj	lass	gaff
    // alga	dahs	asks	gals
    // lags	jagg	alas	jags
    // flak	daff	lakh	dash
    // gala
];
export const bottomRow = [
    // "bcnxv", "zxcm", "mbcnz", "bnvcnm", "zxcv", "vbnm", "mnxz", "nxv", "zmnx", "vbcn", "mvz", "vzxcmvx", "mnbxcvz"
    "zero",
    "zebra",
    "zigzag",
    "zipper",
    "zoo",
    "xenops",
    "xerox",
    "xiphias",
    "crony",
    "coal",
    "code",
    "cola",
    "vacuum",
    "vest",
    "violin",
    "volcano",
    "vote",
    "vowel",
    "balloon",
    "bee",
    "bird",
    "broom",
    "butterfly",
    "navigation",
    "net",
    "nine",
    "number",
    "mitten",
    "moon",
    "mouse",
];

export const punctMarks = [",", ".", "!", "?", ":", ";", "-", "'"];

// SOURCE: https://blog.talaera.com/business-emails-phrases
export const sentences = [
    // BEING SOCIAL
    "I hope this email finds you well.",
    "I hope you had a good weekend.",
    "I hope you had a great trip.",
    "Hope you had a nice break.",
    "I hope you are well.",
    "I hope all is well.",
    "Hope you're enjoying your holiday.",
    "I hope you enjoyed the event.",
    "I'm glad we had a chance to chat at the convention.",
    "It was great to see you on Thursday.",
    "It was a pleasure to meet you yesterday.",
    // REASON OF THE EMAIL
    "I am writing to you about our last meeting.",
    "I am writing to you about your presentation.",
    "I am writing to you about our next event.",
    "I am writing to you with regards to...",
    "I am writing to you concerning...",
    "I am writing to you with regards regarding...",
    "I am writing to you in connection with...",
    // "I am writing to ask/enquire/let you know/confirm/check/invite you to/to update you on/ask for a favor...",
    "I am writing you to follow up on...",
    "I am contacting you to inform...",
    "I am reaching out because...",
    "This is just a quick note to...",
    "This is just a quick reminder...",
    "I wanted to let you know that...",
    "Might I take a moment of your time to... ",
    "This email is just to let you know that...",
    // REPLYING
    "I just got your request for...",
    "I just read your email about...",
    "As we discussed, I would like to send you...",
    "Thank you for your email about...",
    // "Thanks for your feedback on/your invitation/your suggestion",
    "Thanks for sending/asking about/attending",
    "Thanks for your quick reply.",
    "Thanks for getting back to me so quickly.",
    "Thank you for reaching out.",
    // APOLOGISING
    "Sorry for my late reply.",
    "Sorry that it took me so long to get back to you.",
    "I apologize for the late response.",
    "Sorry it’s been so long since my last email.",
    "I was sorry to hear about...",
    // "Please accept our apologies for any inconvenience caused.",
    // "Thank you for your understanding/for your patience.",
    // "Thanks again for your understanding/for your patience.",
    // "Once again, please accept our apologies for any inconvenience caused/for the inconvenience caused/for the delay/for the misunderstanding.",
    "I hope this is okay with you.",
    "I really hope we can find a solution soon.",
    "I hope you can understand.",
    "Sorry I couldn't be of more help.",
    // ATTACHMENTS AND INFORMATION
    "I’ve attached…",
    "Please find [file] attached.",
    "I'm enclosing [file].",
    // "Please see the information below for more details about...",
    // "The parts in bold/in red/in blue are my comments/are the changes we made.",
    "Here's the document that you asked for,",
    "I’ve attached [file] for your review.",
    "I'm sending you [file] as a pdf file.",
    "The attached file contains...",
    // "Could you please sign the attached form and send it back to us by [date]?",
    "Here’s the [document] we discussed.",
    "[file] is attached.",
    "Please take a look at the attached file.",
    // "Take a look at the [file] I've attached to this email.",
    "More information is available at www.talaera.com.",
    "Please note that...",
    // REQUESTS AND INQUIRIES
    "Could you please...?",
    "Could you possibly tell me...?",
    "Can you please fill out this form?",
    "I'd really appreciate it if you could...",
    "I'd be very grateful if you could...",
    "It would be very helpful if you could send us/me...",
    // "I was wondering if you could/if you would be able to...",
    "If possible, I'd like to know (more) about...",
    "Please find my two main questions below.",
    // ASKING FOR CLARIFICATIONS
    "I didn't/don't fully understand [something].",
    "Could you please explain that again?",
    "I didn't quite get your point about [something].",
    "Could you be more specific?",
    "Could you repeat what you said about...?",
    "Could you give us some more details on...?",
    // "If you could please shed some light on this topic, I would really appreciate it.",
    "Could you please clarify [something]?",
    // "Could you please clarify when you would like us to finish this?",
    // "When exactly are you expecting to have this feature?",
    "Here are the details on...",
    // "Could you please clarify what you would like us to do about...?",
    // "If I understood you correctly, you would like me to...",
    "What exactly do you mean by [something]?",
    "Could you explain what you mean by [something]?",
    "In other words, would you like us to...",
    // SHARING INFORMATION
    "Thank you for letting me know.",
    "Thank you for the heads up.",
    "Thank you for the notice.",
    "Please note...",
    "Quick reminder...",
    "Just a quick/friendly reminder that...",
    "Thank you for sharing.",
    "I'd like to inform you that...",
    "Just a quick heads up -",
    "Thanks for keeping me in the loop.",
    // "Please keep me informed/posted/updated/in the loop.",
    // GETTING AND GIVING APPROVAL
    "Please let me know if this is OK with you.",
    "Please let me know what you think.",
    "What are your thoughts (on this)?",
    "What do you think?",
    "We just need the thumbs up/the green light.",
    "You (totally) have the green light!",
    "Please guide me in this regard.",
    // "He approved of it, so you can go ahead with the project.",
    // SCHEDULING
    // "I'd like to schedule a meeting on Monday if you are available/free then.",
    // "I am available on Tuesday, if that's convenient for you.",
    // "Would you be available on Wednesday? If so, I'll send you an invite shortly.",
    // "Can you make it on Thursday? If so, I'll book accordingly.",
    // "I'm afraid I can't make it on Friday. How about Saturday?",
    // "(Due to...) I'm afraid we need to reschedule/delay/postpone/put back/cancel/call off/move/rearrange our meeting.",
    // "We are sorry to inform you that the interview/meeting scheduled for Monday will have to be rescheduled.",
    // GIVING BAD NEWS
    "Unfortunately, we cannot/we are unable to ...",
    "I'm afraid it will not be possible to...",
    "Unfortunately, I have to tell you that...",
    "I'm afraid that we can't...",
    "We regret to inform you that...",
    "I regret to inform you that (due to...) ...",
    // "After careful consideration, we have decided (not) to ...",
    "Due to [reason], it won't be possible to...",
    "It's against company policy to...",
    "I tried my best, but...",
    "Despite my best efforts, ...",
    "I can't see how...",
    "I'm sorry but it's out of my hands.",
    "I'm afraid I won't be able to...",
    "I'm sorry to tell you that...",
    // WHEN SOMETHING IS EXPECTED
    "Looking forward to hearing from you soon.",
    "I look forward to hearing from you soon.",
    "Please let me know if this works.",
    "Please let me know if you are available.",
    "Please let me know if that sounds good.",
    "Please let me know if you can.",
    "Please let me know if you need to reschedule...",
    "I look forward to seeing/meeting you.",
    "See you on Thursday/next week.",
    "Thanks.",
    "Thank you in advance.",
    "Thank you for everything.",
    "Cheers.",
    // "Any feedback you can give me on this would be greatly appreciated.",
    // "Any feedback you can give me on this would be highly appreciated.",
    // "Any feedback you can give me on this would be much appreciated.",
    // "If you could have it ready by tomorrow, I would really appreciate it.",
    // "If you could have it ready by the end of next week, I would really appreciate it.",
    "I would appreciate your help in this matter.",
    // OFFERING HELP OR INFORMATION
    "I hope you find this helpful.",
    "I hope it's clearer now.",
    "I hope that answers all your questions.",
    // "If we can be of any further assistance, please let us know.",
    "Let me know if you need any help.",
    "For further details...",
    "If you have any (more) questions (about)...",
    "In the meantime, if you need any more information,",
    // "If you need more information/more info/further information,",
    // "I know that's a lot to take in, so let me know if anything I've said doesn't make sense.",
    "please do not hesitate to contact me.",
    "please feel free to contact me/to get in touch.",
    "please let me know.",
    "drop me an email/drop me a line. ",
    // FRIENDLY WAYS TO SAY BYE
    "Best regards,",
    "All the best,",
    "Best wishes,",
    "Cheers, ",
    "Have a great weekend!",
    "Have a wonderful day!",
    // PANGRAMS
    "The five boxing wizards jump quickly.",
    "Pack my box with five dozen liquor jugs.",
    "Go, lazy fat vixen; be shrewd, jump quick.",
    "When zombies arrive, quickly fax Judge Pat.",
    "Amazingly few discotheques provide jukeboxes.",
    "Puzzled women bequeath jerks very exotic gifts.",
    "The quick onyx goblin jumps over the lazy dwarf.",
    "Brawny gods just flocked up to quiz and vex him.",
    "Watch “Jeopardy!”, Alex Trebek’s fun TV quiz game.",
    // "Six big devils from Japan quickly forgot how to waltz.",
    // "Five or six big jet planes zoomed quickly by the tower.",
    // "Jack amazed a few girls by dropping the antique onyx vase.",
    // "A quick movement of the enemy will jeopardize six gunboats.",
    // "Jaded zombies acted quaintly but kept driving their oxen forward.",
    // "No kidding—Lorenzo called off his trip to Mexico City just because they told him the conquistadors were extinct.",
    // "Quixotic jugglers repent; wave away fake methods and brazen mishaps.",
    "The quick brown fox jumps over a lazy dog.",
    "Mr. Jock, TV quiz PhD., bags few lynx.",
    "Two driven jocks help fax my big quiz.",
    "Waltz, nymph, for quick jigs vex Bud.",
    "My girl wove six dozen plaid jackets before she quit.",
    // "Sixty zippers were quickly picked from the woven jute bag.",
    "Sphinx of black quartz, judge my vow.",
    "A wizard’s job is to vex chumps quickly in fog.",
    // "Brown jars prevented the mixture from freezing too quickly.",
    "How vexingly quick daft zebras jump!",
    "Jackdaws love my big sphinx of quartz.",
    "GQ’s oft lucky whiz Dr. J, ex-NBA MVP.",
    // "We promptly judged antique ivory buckles for the next prize.",
    "Glib jocks quiz nymph to vex dwarf.",
    "When zombies arrive, quickly fax Judge Pat.",
    "Waxy and quivering, jocks fumble the pizza.",
    "The jay, pig, fox, zebra and my wolves quack!",
    "Pack my box with five dozen liquor jugs.",
    "The five boxing wizards jump quickly.",
    // "Farmer jack realized that big yellow quilts were expensive.",
    // "",
    // "",
    // "",
    // "",
    // "",
    // "",
    // "",
    // "",
    // "",
    // "",
    // "",
    // ""
];

// export default common100;

// BEGINNER KEY LEVELS
export const keysLevel_1 = ["j", "f"];
export const keysLevel_2 = ["u", "r", "k"];
export const keysLevel_3 = ["d", "e", "i"];
export const keysLevel_4 = ["c", "g", "n"];
export const keysLevel_5 = ["t", "s", "l"];
export const keysLevel_6 = ["o", "b", "a"];
export const keysLevel_7 = ["v", "h", "m"];
export const keysLevel_8 = ["w", "x", "q"];
export const keysLevel_9 = ["y", "p", "z"];

export const keyLevelsArray = [
    keysLevel_1,
    keysLevel_2,
    keysLevel_3,
    keysLevel_4,
    keysLevel_5,
    keysLevel_6,
    keysLevel_7,
    keysLevel_8,
    keysLevel_9,
];
